# Generated by Django 4.2.2 on 2023-06-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=50)),
                ('map_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_x', models.FloatField()),
                ('dest_y', models.FloatField()),
                ('source_x', models.FloatField()),
                ('source_y', models.FloatField()),
                ('stand_img', models.URLField(blank=True, null=True)),
                ('aim_img', models.URLField(blank=True, null=True)),
                ('skill_type', models.IntegerField()),
                ('is_attack_sided', models.BooleanField()),
                ('notes', models.TextField(max_length=500)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='lineups_api.playbook')),
            ],
        ),
    ]
