# Generated by Django 4.2.2 on 2023-06-21 04:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='aim_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='stand_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
