# Generated by Django 4.2.2 on 2023-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups_api', '0002_alter_lineup_aim_img_alter_lineup_stand_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='playbook_name',
            field=models.CharField(default='Unnamed Playbook', max_length=50),
            preserve_default=False,
        ),
    ]
