# Generated by Django 4.2.2 on 2023-07-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups_api', '0004_agent_map_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='display_icon',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='minimap',
            field=models.URLField(null=True),
        ),
    ]
