# Generated by Django 4.2.2 on 2023-07-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups_api', '0005_alter_map_display_icon_alter_map_minimap'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='map',
            managers=[
            ],
        ),
    ]
