# Generated by Django 4.2.2 on 2023-07-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups_api', '0006_alter_map_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='abilities',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
