# Generated by Django 4.2.2 on 2023-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups_api', '0007_agent_abilities_delete_ability'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='agent_img',
            field=models.URLField(default='127.0.0.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playbook',
            name='map_img',
            field=models.URLField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
