# Generated by Django 4.2.2 on 2023-07-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups_api', '0008_playbook_agent_img_playbook_map_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbook',
            name='agent_img',
        ),
        migrations.RemoveField(
            model_name='playbook',
            name='map_img',
        ),
    ]
